// Unidades de medida habituales en materiales, almacén, mantenimiento y servicios.
// Los códigos se persisten en minúscula para mantener consistencia en el catálogo.
export const UNIDADES_MEDIDA_MATERIAL = [
  ['und', 'Unidad'],
  ['pza', 'Pieza'],
  ['par', 'Par'],
  ['doc', 'Docena'],
  ['juego', 'Juego (juego)'],
  ['jgo', 'Juego'],
  ['set', 'Set'],
  ['kit', 'Kit'],
  ['caja', 'Caja'],
  ['paquete', 'Paquete'],
  ['bulto', 'Bulto'],
  ['saco', 'Saco'],
  ['fardo', 'Fardo'],
  ['pallet', 'Pallet'],
  ['lote', 'Lote'],
  ['rollo', 'Rollo'],
  ['bobina', 'Bobina'],
  ['carrete', 'Carrete'],
  ['barra', 'Barra'],
  ['plancha', 'Plancha'],
  ['tubo', 'Tubo'],
  ['tambor', 'Tambor'],
  ['balde', 'Balde'],
  ['botella', 'Botella'],
  ['bidon', 'Bidón'],
  ['cilindro', 'Cilindro'],
  ['mg', 'Miligramo'],
  ['g', 'Gramo'],
  ['kg', 'Kilogramo'],
  ['t', 'Tonelada'],
  ['lb', 'Libra'],
  ['oz', 'Onza'],
  ['mm', 'Milímetro'],
  ['cm', 'Centímetro'],
  ['m', 'Metro'],
  ['km', 'Kilómetro'],
  ['pulg', 'Pulgada'],
  ['cm²', 'Centímetro cuadrado'],
  ['m²', 'Metro cuadrado'],
  ['cm³', 'Centímetro cúbico'],
  ['m³', 'Metro cúbico'],
  ['m2', 'Metro cuadrado (m2)'],
  ['m3', 'Metro cúbico (m3)'],
  ['ml', 'Mililitro'],
  ['l', 'Litro (l)'],
  ['lt', 'Litro'],
  ['gal', 'Galón (gal)'],
  ['gl', 'Galón'],
  ['hr', 'Hora'],
  ['hora', 'Hora (hora)'],
  ['dia', 'Día'],
  ['semana', 'Semana'],
  ['mes', 'Mes'],
  ['turno', 'Turno'],
  ['viaje', 'Viaje'],
  ['serv', 'Servicio'],
  ['servicio', 'Servicio (servicio)'],
  ['glb', 'Global'],
];
