-- Ola 4 DIFESMAQ: GAP-01 Reclutamiento + GAP-06/07 autoservicio del empleado.
-- Idempotente. Las tablas nuevas usan aislamiento por tenant y los accesos de autoservicio
-- resuelven la ficha desde auth.uid(), nunca desde un ID arbitrario enviado por UI.

create table if not exists public.rrhh_vacantes (
  id text primary key,
  empresa_id text not null references public.empresas(id) on delete cascade,
  cargo_id text,
  cargo text not null,
  area text,
  sede text,
  descripcion text,
  posiciones integer not null default 1 check (posiciones > 0),
  posiciones_cubiertas integer not null default 0 check (posiciones_cubiertas >= 0),
  fecha_apertura date not null default current_date,
  estado text not null default 'abierta' check (estado in ('abierta','en_proceso','cerrada','cancelada')),
  motivo_cancelacion text,
  public_token text unique,
  creado_por text default auth.uid()::text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.rrhh_candidatos (
  id text primary key,
  empresa_id text not null references public.empresas(id) on delete cascade,
  nombre text not null,
  dni text not null,
  telefono text,
  email text,
  cv_url text,
  cv_path text,
  alerta_historial jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (empresa_id, dni)
);

create table if not exists public.rrhh_candidaturas (
  id text primary key,
  empresa_id text not null references public.empresas(id) on delete cascade,
  vacante_id text not null references public.rrhh_vacantes(id) on delete restrict,
  candidato_id text not null references public.rrhh_candidatos(id) on delete restrict,
  etapa text not null default 'postulado' check (etapa in ('postulado','entrevista','evaluacion','seleccionado','contratado','descartado')),
  fuente text not null default 'interno',
  notas_evaluacion text,
  descarte_motivo text,
  personal_id text,
  personal_tipo text check (personal_tipo is null or personal_tipo in ('operativo','administrativo')),
  creado_por text default auth.uid()::text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.rrhh_candidatura_historial (
  id bigint generated by default as identity primary key,
  empresa_id text not null references public.empresas(id) on delete cascade,
  candidatura_id text not null references public.rrhh_candidaturas(id) on delete cascade,
  etapa_desde text,
  etapa_hasta text not null,
  motivo text,
  notas text,
  usuario_id text default auth.uid()::text,
  fecha timestamptz not null default now()
);

create index if not exists idx_rrhh_vacantes_empresa_estado on public.rrhh_vacantes(empresa_id, estado);
create index if not exists idx_rrhh_candidatos_empresa_dni on public.rrhh_candidatos(empresa_id, dni);
create index if not exists idx_rrhh_candidaturas_empresa_vacante on public.rrhh_candidaturas(empresa_id, vacante_id, etapa);
create index if not exists idx_rrhh_candidatura_historial_candidatura on public.rrhh_candidatura_historial(candidatura_id, fecha);

alter table public.rrhh_vacantes enable row level security;
alter table public.rrhh_candidatos enable row level security;
alter table public.rrhh_candidaturas enable row level security;
alter table public.rrhh_candidatura_historial enable row level security;

drop policy if exists rrhh_vacantes_tenant_select on public.rrhh_vacantes;
create policy rrhh_vacantes_tenant_select on public.rrhh_vacantes
for select using (public.usuario_tiene_empresa(empresa_id) or (estado = 'abierta' and public_token is not null));

drop policy if exists rrhh_vacantes_tenant_write on public.rrhh_vacantes;
create policy rrhh_vacantes_tenant_write on public.rrhh_vacantes
for all using (public.usuario_tiene_empresa(empresa_id) and public.usuario_puede(empresa_id, 'reclutamiento', 'ver'))
with check (public.usuario_tiene_empresa(empresa_id) and public.usuario_puede(empresa_id, 'reclutamiento', 'crear'));

drop policy if exists rrhh_candidatos_tenant_select on public.rrhh_candidatos;
create policy rrhh_candidatos_tenant_select on public.rrhh_candidatos
for select using (public.usuario_tiene_empresa(empresa_id));

drop policy if exists rrhh_candidatos_tenant_write on public.rrhh_candidatos;
create policy rrhh_candidatos_tenant_write on public.rrhh_candidatos
for all using (public.usuario_tiene_empresa(empresa_id) and public.usuario_puede(empresa_id, 'reclutamiento', 'ver'))
with check (public.usuario_tiene_empresa(empresa_id) or auth.role() = 'anon');

drop policy if exists rrhh_candidaturas_tenant_select on public.rrhh_candidaturas;
create policy rrhh_candidaturas_tenant_select on public.rrhh_candidaturas
for select using (public.usuario_tiene_empresa(empresa_id));

drop policy if exists rrhh_candidaturas_tenant_write on public.rrhh_candidaturas;
create policy rrhh_candidaturas_tenant_write on public.rrhh_candidaturas
for all using (public.usuario_tiene_empresa(empresa_id) and public.usuario_puede(empresa_id, 'reclutamiento', 'ver'))
with check (public.usuario_tiene_empresa(empresa_id) or auth.role() = 'anon');

drop policy if exists rrhh_candidatura_historial_tenant_select on public.rrhh_candidatura_historial;
create policy rrhh_candidatura_historial_tenant_select on public.rrhh_candidatura_historial
for select using (public.usuario_tiene_empresa(empresa_id));

drop policy if exists rrhh_candidatura_historial_insert on public.rrhh_candidatura_historial;
create policy rrhh_candidatura_historial_insert on public.rrhh_candidatura_historial
for insert with check (public.usuario_tiene_empresa(empresa_id) or auth.role() = 'anon');

create or replace function public.mover_candidatura_rrhh(
  p_candidatura_id text,
  p_etapa text,
  p_motivo text default null,
  p_notas text default null,
  p_personal_id text default null,
  p_personal_tipo text default null
) returns public.rrhh_candidaturas
language plpgsql
security definer
set search_path = public
as $$
declare
  v_old public.rrhh_candidaturas;
  v_new public.rrhh_candidaturas;
begin
  select * into v_old from public.rrhh_candidaturas where id = p_candidatura_id for update;
  if not found then
    raise exception 'Candidatura no encontrada';
  end if;
  if not public.usuario_tiene_empresa(v_old.empresa_id) then
    raise exception 'Sin acceso al tenant';
  end if;
  if p_etapa = 'descartado' and nullif(trim(coalesce(p_motivo, '')), '') is null then
    raise exception 'El descarte requiere motivo';
  end if;

  update public.rrhh_candidaturas
     set etapa = p_etapa,
         notas_evaluacion = coalesce(p_notas, notas_evaluacion),
         descarte_motivo = case when p_etapa = 'descartado' then p_motivo else descarte_motivo end,
         personal_id = coalesce(p_personal_id, personal_id),
         personal_tipo = coalesce(p_personal_tipo, personal_tipo),
         updated_at = now()
   where id = p_candidatura_id
   returning * into v_new;

  insert into public.rrhh_candidatura_historial(empresa_id, candidatura_id, etapa_desde, etapa_hasta, motivo, notas)
  values (v_old.empresa_id, p_candidatura_id, v_old.etapa, p_etapa, p_motivo, p_notas);

  if p_etapa = 'contratado' and v_old.etapa <> 'contratado' then
    update public.rrhh_vacantes
       set posiciones_cubiertas = least(posiciones, posiciones_cubiertas + 1),
           estado = case when posiciones_cubiertas + 1 >= posiciones then 'cerrada' else estado end,
           updated_at = now()
     where id = v_old.vacante_id;
  end if;

  return v_new;
end;
$$;

alter table public.personal_operativo
  add column if not exists dias_vacaciones_disponibles numeric(8,2) default 0;

create or replace function public.resolver_mi_personal_rrhh()
returns table (
  empresa_id text,
  personal_id text,
  personal_tipo text,
  nombre text,
  documento text,
  email text,
  telefono text,
  cargo text,
  area text,
  sede text,
  fecha_ingreso date,
  fecha_fin_contrato date,
  regimen_jornada text,
  dias_ciclo_trabajo integer,
  dias_ciclo_descanso integer,
  dias_vacaciones_disponibles numeric
)
language sql
security definer
set search_path = public
as $$
  select p.empresa_id, p.id, 'operativo', p.nombre, p.documento, p.email, p.telefono, p.cargo, p.area, p.sede,
         p.fecha_ingreso, p.fecha_fin_contrato, p.regimen_jornada, p.dias_ciclo_trabajo, p.dias_ciclo_descanso, p.dias_vacaciones_disponibles
    from public.personal_operativo p
   where p.auth_user_id::text = auth.uid()::text
      or lower(coalesce(p.email, '')) = lower(coalesce((auth.jwt() ->> 'email'), ''))
  union all
  select p.empresa_id, p.id, 'administrativo', p.nombre, coalesce(p.documento, p.dni), p.email, p.telefono, p.cargo, p.area, p.sede,
         p.fecha_ingreso, p.fecha_fin_contrato, p.regimen_jornada, p.dias_ciclo_trabajo, p.dias_ciclo_descanso, p.dias_vacaciones_disponibles
    from public.personal_administrativo p
   where p.auth_user_id::text = auth.uid()::text
      or lower(coalesce(p.email, '')) = lower(coalesce((auth.jwt() ->> 'email'), ''))
  limit 1;
$$;

create or replace function public.es_mi_personal_rrhh(p_empresa_id text, p_personal_id text)
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.resolver_mi_personal_rrhh() f
    where f.empresa_id = p_empresa_id and f.personal_id = p_personal_id
  );
$$;

drop policy if exists personal_documentos_self_select on public.personal_documentos;
create policy personal_documentos_self_select on public.personal_documentos
for select using (public.es_mi_personal_rrhh(empresa_id, personal_id));

drop policy if exists solicitudes_rrhh_self_select on public.solicitudes_rrhh;
create policy solicitudes_rrhh_self_select on public.solicitudes_rrhh
for select using (public.es_mi_personal_rrhh(empresa_id, personal_id));

drop policy if exists registros_asistencia_self_select on public.registros_asistencia;
create policy registros_asistencia_self_select on public.registros_asistencia
for select using (public.es_mi_personal_rrhh(empresa_id, trabajador_id));

drop policy if exists prestamos_personal_self_select on public.prestamos_personal;
create policy prestamos_personal_self_select on public.prestamos_personal
for select using (public.es_mi_personal_rrhh(empresa_id, trabajador_id));

alter table public.amonestaciones_personal
  add column if not exists acusado_en timestamptz,
  add column if not exists acusado_por_user_id text;

drop policy if exists amonestaciones_personal_self_select on public.amonestaciones_personal;
create policy amonestaciones_personal_self_select on public.amonestaciones_personal
for select using (public.es_mi_personal_rrhh(empresa_id, personal_id));

drop policy if exists he_comp_self_select on public.horas_extra_compensacion;
create policy he_comp_self_select on public.horas_extra_compensacion
for select using (public.es_mi_personal_rrhh(empresa_id, personal_id));

alter table public.usuarios_empresas
  drop constraint if exists usuarios_empresas_perfil_campo_check;

alter table public.usuarios_empresas
  add constraint usuarios_empresas_perfil_campo_check
  check (
    perfil_campo is null or perfil_campo in (
      'Técnico', 'Tecnico', 'TÃ©cnico',
      'Vendedor', 'Compras', 'Comprador', 'Supervisor', 'Gerencia',
      'Logistica', 'Logística', 'LogÃ­stica', 'Asistencia',
      'Administrativo', 'Empleado',
      'tecnico', 'técnico', 'tÃ©cnico',
      'vendedor', 'compras', 'comprador', 'supervisor', 'gerencia',
      'logistica', 'logística', 'logÃ­stica', 'asistencia',
      'administrativo', 'empleado',
      'plataforma'
    )
  );

comment on table public.rrhh_vacantes is 'GAP-01 Reclutamiento: vacantes con link publico revocable por estado/token.';
comment on table public.rrhh_candidatura_historial is 'Historial append-only de movimientos del pipeline de postulantes.';
comment on function public.resolver_mi_personal_rrhh() is 'GAP-06/07 autoservicio: resuelve la ficha propia desde auth.uid/email; las UIs no envian personal_id arbitrario.';
